"""
LABYRINTH — the deterministic Game Engine.

Implements Master Rulebook chapters 1-10 and appendices A-F, following the
turn resolution order in 1.6 and the information discipline in 9.4/9.5.

The engine is the only thing that knows the canonical state. Player AIs only
ever receive the filtered perception payload built in perception.py.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence, Set, Tuple

from . import data
from .actions import Action, ActionType, AGGRESSIVE, MECHANICS, parse_action
from .models import (DriveState, GameState, Health, HidingSpot, Item,
                     ObjectiveStatus, Player, Progress, Room)
from .perception import build_perception_payload
from .social_memory import initialize_social_memory, parse_social_memory_update

# Noise generated by the action itself, before the room baseline is applied.
ACTION_NOISE = {
    ActionType.MOVE: 20,
    ActionType.SEARCH: 30,
    ActionType.HIDE: 10,
    ActionType.UNHIDE: 10,
    ActionType.WAIT: 0,
    ActionType.PICKUP: 10,
    ActionType.DROP: 10,
    ActionType.TRADE: 10,
    ActionType.USE_ITEM: 20,
    ActionType.HIDE_ITEM: 15,
    ActionType.DESTROY_ITEM: 45,
    ActionType.ROOM_INTERACT: 45,
    ActionType.ATTACK_KNIFE: 55,
    ActionType.ATTACK_UNARMED: 90,
    ActionType.USE_FINAL_RECORD: 15,
    ActionType.PUSH_FALL: 65,
    ActionType.EXAMINE_BODY: 15,
    ActionType.FLEE: 40,
    ActionType.ESCAPE: 70,
}


def loudness_word(value: int) -> str:
    if value >= 85:
        return "very loud"
    if value >= 60:
        return "loud"
    if value >= 35:
        return "clear but muffled"
    return "faint"


class LabyrinthEngine:
    """Runs a full game of Labyrinth."""

    def __init__(self,
                 brains: Sequence[Any],
                 seed: int = 7,
                 max_turns: int = 60,
                 key_model: str = "permanent",
                 verbose: bool = True) -> None:
        import random
        if len(brains) != 8:
            raise ValueError("A standard game needs exactly 8 player brains.")
        self.verbose = verbose
        self.state = GameState(rng=random.Random(seed), max_turns=max_turns)
        self.state.key_model = key_model
        self.brains = list(brains)
        self.transcript: List[str] = []
        self.interrupted: Set[int] = set()
        self.setup()

    # ------------------------------------------------------------------ #
    # OUTPUT
    # ------------------------------------------------------------------ #
    def say(self, text: str) -> None:
        self.transcript.append(text)
        if self.verbose:
            print(text)

    def notify(self, player: Player, text: str) -> None:
        """Give one player a private, in-world line (9.5)."""
        player.narration.append(text)
        player.remember(text, self.state.turn)

    def notify_room(self, room: str, text: str, exclude: Sequence[int] = ()) -> None:
        for p in self.state.players_in(room):
            if p.id not in exclude:
                self.notify(p, text)

    # ------------------------------------------------------------------ #
    # SETUP  (Engine Prompt section 4)
    # ------------------------------------------------------------------ #
    def setup(self) -> None:
        st = self.state
        st.rooms = self.build_room_graph()
        st.drives = {n: DriveState(name=f"Drive {n}") for n in ("A", "B", "C")}

        for i in range(1, 9):
            p = Player(id=i, name=f"Player {i}", location="Entrance Hall",
                       traits=list(data.PLAYER_TRAITS[i]))
            p.brain = self.brains[i - 1]
            p.social_memory = initialize_social_memory(i - 1, num_players=8)
            st.players.append(p)

        objectives = list(data.OBJECTIVES.keys())
        st.rng.shuffle(objectives)
        for p, oid in zip(st.players, objectives):
            p.objective_id = oid

        # Objective 7 needs a specific victim.
        for p in st.players:
            if p.objective_id == 7:
                others = [q.id for q in st.players if q.id != p.id]
                p.assassination_target = st.rng.choice(others)

        self.place_items()

        for p in st.players:
            self.send_briefing(p)

        self.say("=" * 72)
        self.say("LABYRINTH — game start")
        self.say(f"Vault Key model: {st.key_model} "
                 f"({'opens the gate permanently for everyone' if st.key_model == 'permanent' else 'consumed by the first user'})")
        self.say(f"Rooms: {len(st.rooms)} | Players: {len(st.players)} | Max turns: {st.max_turns}")
        self.say("=" * 72)

    def build_room_graph(self) -> Dict[str, Room]:
        rooms: Dict[str, Room] = {}
        for name, (noise, spots, notes) in data.ROOM_TABLE.items():
            rooms[name] = Room(
                name=name,
                noise=noise,
                notes=notes,
                hiding_spots=[HidingSpot(sname, cap) for sname, cap in spots.items()],
            )
        # Bidirectional edges (Appendix A footnote).
        for src, dests in data.RAW_CONNECTIONS.items():
            if src not in rooms:
                raise KeyError(f"Unknown room in map: {src}")
            for dst in dests:
                if dst not in rooms:
                    raise KeyError(f"Unknown room in map: {dst}")
                if dst not in rooms[src].connections:
                    rooms[src].connections.append(dst)
                if src not in rooms[dst].connections:
                    rooms[dst].connections.append(src)
        return rooms

    def place_items(self) -> None:
        st = self.state
        rng = st.rng

        # 8 role items, spread out (Engine Prompt 4.4)
        role_rooms = ["Library", "Security Office", "Medical Room", "Workshop",
                      "Storage Room", "Observatory", "Archive", "Dormitory"]
        rng.shuffle(role_rooms)
        for (role, (item_name, _)), room_name in zip(data.ROLES.items(), role_rooms):
            item = Item(item_name, kind="role_item", unique=True, data={"role": role})
            st.rooms[room_name].hidden_items.append(item)

        # Drives A/B/C — never all in one place, never in the Data Centre/Vault
        drive_rooms = ["Laboratory", "Maintenance Tunnels", "Hidden Chamber",
                       "Water Reservoir", "Armoury", "Kitchen/Dining Hall"]
        rng.shuffle(drive_rooms)
        for letter, room_name in zip("ABC", drive_rooms[:3]):
            st.rooms[room_name].hidden_items.append(
                Item(f"Drive {letter}", kind="drive", unique=True, data={"letter": letter}))

        # The Knife
        knife_room = rng.choice(["Kitchen/Dining Hall", "Workshop", "Armoury",
                                 "Storage Room", "Laboratory"])
        st.rooms[knife_room].hidden_items.append(Item("Knife", kind="weapon", unique=True))

        # Vault Key and Final Record
        st.rooms["Vault"].hidden_items.append(Item("Vault Key", kind="key", unique=True))
        st.rooms["Hidden Shrine"].hidden_items.append(
            Item("Final Record", kind="final_record", unique=True))

        # Clue chain (Appendix D)
        st.rooms["Library"].mechanic_state["clue"] = data.CLUE_LIBRARY
        st.rooms["Archive"].mechanic_state["clue"] = data.CLUE_ARCHIVE
        st.rooms["Hidden Chamber"].mechanic_state["clue"] = data.CLUE_MECHANISM
        st.rooms["Vault"].mechanic_state["clue"] = data.CLUE_MECHANISM

        # Flavour items (Appendix F)
        for room_name, names in data.FLAVOR_ITEMS.items():
            for n in names:
                kind = "consumable" if n in data.HEALING_ITEMS else "misc"
                st.rooms[room_name].items.append(Item(n, kind=kind))

    def send_briefing(self, p: Player) -> None:
        traits = "; ".join(f"you catch yourself {data.TRAITS[t][0]} when {data.TRAITS[t][1].lower()}"
                           for t in p.traits)
        lines = [
            "You wake in the Entrance Hall of the labyrinth. Cold air, dim light, "
            "seven other people you do not know.",
            f"Your secret objective: {data.OBJECTIVES[p.objective_id]}",
        ]
        if p.assassination_target:
            lines.append(f"Your assigned target is Player {p.assassination_target}.")
        lines.append(f"Habits you know you have: {traits}.")
        lines.append("Only the Exit Gate leads out, and it is locked.")
        for line in lines:
            self.notify(p, line)

    # ------------------------------------------------------------------ #
    # MAIN LOOP
    # ------------------------------------------------------------------ #
    def run(self) -> Dict[str, Any]:
        while not self.state.game_over:
            self.run_turn()
            self.state.game_over = self.check_end_condition()
            self.state.turn += 1
        return self.final_results()

    def run_turn(self) -> None:
        st = self.state
        st.turn_events = []
        actors = st.active_players()
        self.say(f"\n----- TURN {st.turn} -----  active: "
                 f"{', '.join('P%d' % p.id for p in actors) or 'nobody'}")

        # 1. COLLECT (parallel, nobody sees anyone else's choice) — 1.5
        actions: Dict[int, Action] = {}
        for p in actors:
            payload = build_perception_payload(st, p)
            p.narration = []          # consumed; start fresh for this turn
            try:
                raw = p.brain.decide(payload)
            except Exception as exc:                      # a broken brain must not kill the game
                self.log_engine_error(p, exc)
                raw = {"action": "WAIT", "reasoning": "confused"}
            actions[p.id] = parse_action(raw)
            
            # Parse and apply social memory updates from the player's response
            if isinstance(raw, str) and p.social_memory:
                parse_social_memory_update(raw, p.social_memory)

        # Who is being acted against this turn? Needed for interruptions (5.12).
        self.interrupted: Set[int] = set()
        for pid, act in actions.items():
            if act.type in AGGRESSIVE and act.target_player is not None:
                self.interrupted.add(act.target_player)

        # 2. RESOLVE IN FIXED ORDER — 1.6
        self.resolve_speech(actions)
        self.resolve_movement(actions)
        self.resolve_room_interactions(actions)
        self.resolve_searching(actions)
        self.resolve_item_interactions(actions)
        self.resolve_combat(actions)
        self.resolve_environment(actions)
        self.process_deaths()
        self.generate_evidence()
        self.propagate_sound(actions)
        self.activate_traits(actions)
        self.advance_interruptible_actions()
        self.resolve_escapes(actions)

        # 3. OBJECTIVES / EXPOSURE
        self.check_objective_completion()
        self.check_objective_exposure()

        # 4. TURN SUMMARY for the human watching (never sent to players)
        for p in st.players:
            if p.narration:
                self.say(f"  P{p.id} ({p.location}): " + " | ".join(p.narration[-4:]))

    def log_engine_error(self, p: Player, exc: Exception) -> None:
        self.state.log("brain_error", player=p.id, error=repr(exc))
        self.say(f"  [engine] Player {p.id}'s brain failed ({exc!r}); it waits instead.")

    # ------------------------------------------------------------------ #
    # RESOLUTION STEPS
    # ------------------------------------------------------------------ #
    def resolve_speech(self, actions: Dict[int, Action]) -> None:
        """Free action (5.3/5.7): heard by everyone in the same room."""
        st = self.state
        for pid, act in actions.items():
            speaker = st.player(pid)
            if not speaker or not speaker.active:
                continue
            listeners = [q for q in st.players_in(speaker.location) if q.id != pid]

            if act.speech:
                for q in listeners:
                    self.notify(q, f'Player {pid} says: "{act.speech}"')
                st.log("speech", player=pid, room=speaker.location, text=act.speech)

            if act.reveal_role and speaker.role:
                for q in listeners:
                    self.notify(q, f"Player {pid} states their role: {speaker.role}.")
                    q.known_roles[pid] = speaker.role      # truthful, so it is knowledge
                    q.role_beliefs[pid] = speaker.role
                st.log("role_reveal", player=pid, role=speaker.role)

            if act.accusation and listeners:
                tgt = act.accusation.get("player")
                obj = act.accusation.get("objective")
                if tgt and obj and st.player(tgt):
                    speaker.accusations[tgt] = obj
                    for q in listeners:
                        self.notify(q, f"Player {pid} accuses Player {tgt} of pursuing "
                                       f"objective #{obj}: {data.OBJECTIVES.get(obj, '?')}")
                    st.log("accusation", player=pid, target=tgt, objective=obj)

    def resolve_movement(self, actions: Dict[int, Action]) -> None:
        st = self.state
        for pid, act in actions.items():
            p = st.player(pid)
            if not p or not p.active:
                continue

            if act.type in (ActionType.MOVE, ActionType.FLEE):
                # A player locked in an unarmed fight must break away first (Appendix B).
                if p.fight_with is not None:
                    if st.rng.random() < 0.5:
                        opponent = st.player(p.fight_with)
                        self.end_fight(p, opponent, reason="broke away")
                        self.notify(p, "You tear yourself free of the struggle.")
                    else:
                        self.notify(p, "You try to break away but they hold on to you.")
                        continue

                dest = act.target
                if act.type == ActionType.FLEE and not dest:
                    dest = st.rng.choice(st.rooms[p.location].connections)
                if not dest or dest not in st.rooms:
                    self.notify(p, "That is not a place you can walk to from here.")
                    continue
                if dest not in st.rooms[p.location].connections:
                    self.notify(p, f"There is no direct way from {p.location} to {dest}.")
                    continue

                self.leave_hiding(p, quiet=True)
                origin = p.location
                p.location = dest
                p.progress = None                      # walking away abandons timed work
                self.notify(p, f"You move from {origin} to {dest}.")
                for q in st.players_in(origin):
                    if q.id != pid and not q.hiding_in:
                        self.notify(q, f"Player {pid} leaves towards {dest}.")
                for q in st.players_in(dest):
                    if q.id != pid and not q.hiding_in:
                        self.notify(q, f"Player {pid} arrives from {origin}.")
                st.log("move", player=pid, frm=origin, to=dest)

            elif act.type == ActionType.HIDE:
                room = st.rooms[p.location]
                spot = room.spot(act.target) if act.target else room.free_spot()
                if spot is None or spot.full:
                    spot = room.free_spot()
                if spot is None:
                    self.notify(p, "There is nowhere here to hide.")
                    continue
                self.leave_hiding(p, quiet=True)
                spot.occupants.append(p.id)
                p.hiding_in = spot.name
                self.notify(p, f"You slip into concealment: {spot.name}.")
                st.log("hide", player=pid, room=room.name, spot=spot.name)

            elif act.type == ActionType.UNHIDE:
                if p.hiding_in:
                    self.leave_hiding(p)
                else:
                    self.notify(p, "You were not hidden.")

    def leave_hiding(self, p: Player, quiet: bool = False) -> None:
        if not p.hiding_in:
            return
        room = self.state.rooms[p.location]
        spot = room.spot(p.hiding_in)
        if spot and p.id in spot.occupants:
            spot.occupants.remove(p.id)
        p.hiding_in = None
        if not quiet:
            self.notify(p, "You step out of hiding.")
            for q in self.state.players_in(room.name):
                if q.id != p.id:
                    self.notify(q, f"Player {p.id} steps out of hiding.")

    # -- room mechanics ---------------------------------------------------
    def resolve_room_interactions(self, actions: Dict[int, Action]) -> None:
        st = self.state
        for pid, act in actions.items():
            p = st.player(pid)
            if not p or not p.active or act.type != ActionType.ROOM_INTERACT:
                continue
            mech = (act.target or "").strip().lower()
            if mech not in MECHANICS:
                self.notify(p, "You cannot do that here.")
                continue
            getattr(self, f"_mech_{mech}")(p, act)

    def _mech_toggle_power(self, p: Player, act: Action) -> None:
        st = self.state
        if p.location != "Generator Room":
            self.notify(p, "There is no generator here.")
            return
        st.power_on = not st.power_on
        self.notify(p, f"You throw the breaker. Power is now {'ON' if st.power_on else 'OFF'}.")
        st.log("power", player=p.id, on=st.power_on)
        for q in st.players:
            if q.active and q.id != p.id:
                self.notify(q, "The lights " + ("come back on." if st.power_on else "die. Darkness."))

    def _mech_check_cameras(self, p: Player, act: Action) -> None:
        st = self.state
        if p.location != "Security Office":
            self.notify(p, "There are no monitors here.")
            return
        if not st.power_on:
            self.notify(p, "The monitors are dead — no power.")
            return
        seen = []
        for room in data.CAMERA_ROOMS:
            people = [q for q in st.players_in(room) if not q.hiding_in]
            if people:
                seen.append(f"{room}: " + ", ".join(f"Player {q.id}" for q in people))
        self.notify(p, "Camera feeds — " + ("; ".join(seen) if seen else "every watched room is empty."))
        st.log("cameras", player=p.id)

    def _mech_process_drive(self, p: Player, act: Action) -> None:
        st = self.state
        if p.location != "Data Centre":
            self.notify(p, "There is no terminal here to read a drive.")
            return
        drive = next((i for i in p.inventory if i.kind == "drive"), None)
        if act.raw.get("drive"):
            drive = p.has_item(str(act.raw["drive"])) or drive
        if not drive:
            self.notify(p, "You are not carrying a drive to insert.")
            return
        self.start_or_continue(p, "process_drive", target=drive.name,
                               msg=f"You slot {drive.name} into the terminal. It begins reading.")

    def _mech_destroy_drive(self, p: Player, act: Action) -> None:
        if p.location not in ("Furnace", "Boiler Room"):
            self.notify(p, "Nothing here burns hot enough to destroy a drive.")
            return
        drive = next((i for i in p.inventory if i.kind == "drive"), None)
        if not drive:
            self.notify(p, "You are not carrying a drive.")
            return
        self.start_or_continue(p, "destroy_drive", target=drive.name,
                               msg=f"You hold {drive.name} to the heat.")

    def _mech_solve_mechanism(self, p: Player, act: Action) -> None:
        if p.location != "Vault":
            self.notify(p, "The escape mechanism is not here.")
            return
        if data.CLUE_MECHANISM not in p.clues:
            self.notify(p, "The mechanism is a nest of dials you do not understand. "
                           "Something written down somewhere must explain it.")
            return
        self.start_or_continue(p, "solve_mechanism", target="vault mechanism",
                               msg="You begin working the mechanism through its sequence.")

    def _mech_open_gate(self, p: Player, act: Action) -> None:
        st = self.state
        if p.location != "Exit Gate":
            self.notify(p, "The gate is not here.")
            return
        if st.gate_open:
            self.notify(p, "The gate already stands open.")
            return
        key = p.has_item("Vault Key")
        if not key:
            self.notify(p, "The gate is locked and you have no key.")
            return
        if st.key_model == "permanent":
            st.gate_open = True
            self.notify(p, "The key turns. The Exit Gate grinds open — and stays open.")
            for q in st.active_players():
                if q.id != p.id:
                    self.notify(q, "Somewhere far off, a heavy gate grinds open.")
        else:
            p.take("Vault Key")
            self.notify(p, "The key turns, then snaps off in the lock. The way out is yours alone.")
            p.data_gate_pass = True  # type: ignore[attr-defined]
        st.log("gate_open", player=p.id, model=st.key_model)

    def _mech_look_through_telescope(self, p: Player, act: Action) -> None:
        if p.location != "Observatory":
            self.notify(p, "There is nothing to look through here.")
            return
        self.state.rooms["Observatory"].mechanic_state.setdefault("at_edge", set()).add(p.id)
        self.notify(p, "You lean out over the rail to look. The drop below is a long one.")
        for q in self.state.players_in("Observatory"):
            if q.id != p.id:
                self.notify(q, f"Player {p.id} leans out over the edge.")

    def _mech_rest(self, p: Player, act: Action) -> None:
        self.notify(p, "You sit and breathe for a while. Nothing changes.")

    def _mech_heal(self, p: Player, act: Action) -> None:
        supply = p.has_item("Medical Supplies") or p.has_item("Bandages")
        in_medbay = p.location == "Medical Room"
        if p.health != Health.INJURED:
            self.notify(p, "You are not wounded.")
            return
        if not (supply or in_medbay):
            self.notify(p, "You have nothing to treat the wound with.")
            return
        if supply:
            p.inventory.remove(supply)
        p.health = Health.HEALTHY
        self.notify(p, "You clean and bind the wound. You are steady again.")
        self.state.log("heal", player=p.id)

    def start_or_continue(self, p: Player, kind: str, target: str, msg: str) -> None:
        """Begin a timed action, or keep an existing one alive this turn (5.17)."""
        if p.progress and p.progress.kind == kind and p.progress.room == p.location:
            p.progress.target = target
            self.notify(p, "You keep working.")
        else:
            p.progress = Progress(kind=kind, seconds_left=data.DURATIONS[kind],
                                  room=p.location, target=target)
            self.notify(p, msg)
        p.progress_touched_this_turn = True  # type: ignore[attr-defined]

    # -- searching --------------------------------------------------------
    def resolve_searching(self, actions: Dict[int, Action]) -> None:
        st = self.state
        for pid, act in actions.items():
            p = st.player(pid)
            if not p or not p.active or act.type != ActionType.SEARCH:
                continue
            room = st.rooms[p.location]
            chance = 0.60
            if p.role == "Investigator":
                chance += 0.25
            if p.role == "Scavenger":
                chance += 0.25
            if not st.power_on and room.name not in ("Courtyard", "Observatory"):
                chance -= 0.20

            found_any = False

            # hidden items
            for item in list(room.hidden_items):
                if st.rng.random() < chance:
                    if item.name == "Final Record" and data.CLUE_ARCHIVE not in p.clues:
                        self.notify(p, "You find a sealed reliquary. Its lock answers to a "
                                       "sequence you have not learned yet.")
                        continue
                    room.hidden_items.remove(item)
                    room.items.append(item)
                    self.notify(p, f"You uncover: {item.name}.")
                    st.log("found_item", player=pid, item=item.name, room=room.name)
                    found_any = True

            # clue chain
            clue = room.mechanic_state.get("clue")
            if clue and clue not in p.clues and st.rng.random() < chance + 0.15:
                if clue == data.CLUE_ARCHIVE and data.CLUE_LIBRARY not in p.clues:
                    self.notify(p, "The shelves reference an index you have not seen.")
                else:
                    p.clues.add(clue)
                    found_any = True
                    self.notify(p, self.clue_text(clue))
                    st.log("found_clue", player=pid, clue=clue, room=room.name)

            # hidden players
            for spot in room.hiding_spots:
                for hid in list(spot.occupants):
                    if hid != pid and st.rng.random() < chance:
                        other = st.player(hid)
                        if other:
                            self.leave_hiding(other)
                            self.notify(p, f"You pull back the {spot.name} — Player {hid} is there.")
                            self.notify(other, f"Player {pid} finds your hiding place.")
                            found_any = True

            # evidence
            if room.evidence and st.rng.random() < chance:
                self.notify(p, "You find traces: " + "; ".join(room.evidence))
                found_any = True

            if not found_any:
                self.notify(p, f"You search {room.name} and turn up nothing useful.")

    def clue_text(self, clue: str) -> str:
        if clue == data.CLUE_LIBRARY:
            return ("Pressed inside a ledger: a note. 'What was taken from the shelves "
                    "was written down in the Archive.'")
        if clue == data.CLUE_ARCHIVE:
            return ("A second note, in the same hand: 'What the Archive recorded is kept "
                    "at the shrine below the tunnels.'")
        return ("A folded diagram of the Vault's dial sequence. You could work the escape "
                "mechanism now, given time.")

    # -- items ------------------------------------------------------------
    def resolve_item_interactions(self, actions: Dict[int, Action]) -> None:
        st = self.state
        # 9.6 - two players reaching for the same item is resolved together,
        # never by who was asked first.
        contested: Dict[Tuple[str, str], List[int]] = {}
        for pid, act in actions.items():
            p = st.player(pid)
            if p and p.active and act.type == ActionType.PICKUP and act.target:
                contested.setdefault((p.location, act.target.lower()), []).append(pid)
        winners = {key: (ids[0] if len(ids) == 1 else st.rng.choice(ids))
                   for key, ids in contested.items()}

        for pid, act in actions.items():
            p = st.player(pid)
            if not p or not p.active:
                continue
            room = st.rooms[p.location]

            if act.type == ActionType.PICKUP:
                key = (p.location, (act.target or "").lower())
                if winners.get(key, pid) != pid:
                    other = winners[key]
                    self.notify(p, f"Player {other} gets a hand to it first.")
                    continue
                item = room.find_item(act.target or "")
                if not item:
                    self.notify(p, "There is nothing like that within reach here.")
                    continue
                if len(p.inventory) >= p.inventory_limit:
                    self.notify(p, "Your hands are full — you would have to drop something.")
                    continue
                room.items.remove(item)
                if item.kind == "role_item":
                    self.claim_role(p, item)
                else:
                    p.inventory.append(item)
                    self.notify(p, f"You take the {item.name}.")
                    for q in st.players_in(room.name):
                        if q.id != pid and not q.hiding_in:
                            self.notify(q, f"Player {pid} picks up the {item.name}.")
                st.log("pickup", player=pid, item=item.name, room=room.name)

            elif act.type == ActionType.DROP:
                item = p.take(act.target or "")
                if not item:
                    self.notify(p, "You are not carrying that.")
                    continue
                room.items.append(item)
                self.notify(p, f"You put down the {item.name}.")
                self.notify_room(room.name, f"Player {pid} sets down a {item.name}.", exclude=[pid])

            elif act.type == ActionType.HIDE_ITEM:
                item = p.take(act.target or "")
                if not item:
                    self.notify(p, "You are not carrying that.")
                    continue
                room.hidden_items.append(item)
                self.notify(p, f"You stash the {item.name} out of sight.")

            elif act.type == ActionType.TRADE:
                other = st.player(act.target_player or -1)
                item = p.has_item(act.target or "")
                if not other or other.location != p.location or not other.active:
                    self.notify(p, "They are not here.")
                    continue
                if not item:
                    self.notify(p, "You are not carrying that.")
                    continue
                if len(other.inventory) >= other.inventory_limit:
                    self.notify(p, "They have no room to carry it.")
                    continue
                p.inventory.remove(item)
                other.inventory.append(item)
                self.notify(p, f"You hand the {item.name} to Player {other.id}.")
                self.notify(other, f"Player {pid} hands you the {item.name}.")
                st.log("trade", player=pid, to=other.id, item=item.name)

            elif act.type == ActionType.USE_ITEM:
                item = p.has_item(act.target or "")
                if not item:
                    self.notify(p, "You are not carrying that.")
                    continue
                if item.name in data.HEALING_ITEMS and p.health == Health.INJURED:
                    p.inventory.remove(item)
                    p.health = Health.HEALTHY
                    self.notify(p, f"You use the {item.name}. The bleeding stops.")
                else:
                    self.notify(p, f"You turn the {item.name} over in your hands. Nothing happens.")

            elif act.type == ActionType.DESTROY_ITEM:
                self.notify(p, "Only the Furnace or Boiler Room can destroy anything that matters.")

            elif act.type == ActionType.EXAMINE_BODY:
                self.examine_body(p, act)

    def claim_role(self, p: Player, item: Item) -> None:
        """4.13 — the item vanishes and the role becomes permanent and exclusive."""
        st = self.state
        role = item.data["role"]
        if p.role:
            st.rooms[p.location].items.append(item)
            self.notify(p, f"You already carry a role. You leave the {item.name}.")
            return
        p.role = role
        if role == "Scavenger":
            self.notify(p, "The backpack lets you carry more.")
        self.notify(p, f"You take up the {item.name}. You are now the {role}. "
                       f"{data.ROLES[role][1]}")
        for q in st.players_in(p.location):
            if q.id != p.id:
                self.notify(q, f"Player {p.id} takes a {item.name} and pockets it.")
                q.known_roles[p.id] = role          # they saw the item: real knowledge
                q.role_beliefs[p.id] = role
        st.log("role_claim", player=p.id, role=role)

    def examine_body(self, p: Player, act: Action) -> None:
        st = self.state
        bodies = [q for q in st.players
                  if q.location == p.location and q.health == Health.DEAD]
        if not bodies:
            self.notify(p, "There is no body here.")
            return
        body = bodies[0]
        if act.target_player:
            body = next((b for b in bodies if b.id == act.target_player), body)
        cause = getattr(body, "death_cause", "unclear")
        if p.role == "Forensic Analyst":
            self.notify(p, f"Player {body.id}: killed by {cause} on turn "
                           f"{body.finish_turn}. Traces nearby: "
                           f"{'; '.join(st.rooms[p.location].evidence) or 'none'}.")
        else:
            self.notify(p, f"Player {body.id} is dead. You cannot tell much more than that.")

    # -- combat -----------------------------------------------------------
    def resolve_combat(self, actions: Dict[int, Action]) -> None:
        st = self.state

        # continue running unarmed fights first (Appendix B)
        for p in list(st.players):
            if p.fight_with is not None and p.active:
                opp = st.player(p.fight_with)
                if not opp or not opp.active or opp.location != p.location:
                    self.end_fight(p, opp, reason="lost contact")
                    continue
                if p.id < opp.id:                      # tick each fight once
                    p.fight_seconds += data.TURN_SECONDS
                    opp.fight_seconds = p.fight_seconds
                    self.notify(p, "The struggle goes on.")
                    self.notify(opp, "The struggle goes on.")
                    if p.fight_seconds >= data.DURATIONS["unarmed_fight"]:
                        self.finish_unarmed_fight(p, opp)

        for pid, act in actions.items():
            attacker = st.player(pid)
            if not attacker or not attacker.active or act.type not in AGGRESSIVE:
                continue
            target = st.player(act.target_player or -1)
            if not target or not target.active:
                self.notify(attacker, "Your target is not here.")
                continue
            if target.location != attacker.location:
                self.notify(attacker, "They are no longer in the room.")
                continue

            aware = self.is_aware(target, attacker, actions)

            if act.type == ActionType.ATTACK_KNIFE:
                self.knife_attack(attacker, target, aware)
            elif act.type == ActionType.ATTACK_UNARMED:
                self.begin_unarmed_fight(attacker, target)
            elif act.type == ActionType.PUSH_FALL:
                self.push_fall(attacker, target, aware)
            elif act.type == ActionType.USE_FINAL_RECORD:
                self.write_final_record(attacker, target, act)

    def is_aware(self, target: Player, attacker: Player, actions: Dict[int, Action]) -> bool:
        """6.10 — a genuinely unaware target cannot defend itself."""
        if attacker.hiding_in:
            return False
        their = actions.get(target.id)
        if their and their.target_player == attacker.id and their.type in AGGRESSIVE:
            return True
        if their and their.type in (ActionType.FLEE, ActionType.WAIT):
            return True
        chance = 0.5 + (0.3 if target.role == "Observer" else 0.0)
        return self.state.rng.random() < chance

    def knife_attack(self, attacker: Player, target: Player, aware: bool) -> None:
        st = self.state
        knife = attacker.has_item("Knife")
        if not knife:
            self.notify(attacker, "You have no knife.")
            return
        self.leave_hiding(attacker, quiet=True)
        if not aware or st.rng.random() < 0.70:
            self.notify(attacker, f"The knife goes in before Player {target.id} can turn. They drop.")
            self.notify(target, "Something cold and fast — and then nothing.")
            self.kill(target, cause="a knife wound", killer=attacker)
        else:
            attacker.health = Health.INJURED if attacker.health == Health.HEALTHY else attacker.health
            self.notify(attacker, f"Player {target.id} sees it coming and turns the blade aside. "
                                  "You are hurt in the scramble.")
            self.notify(target, f"Player {pid_str(attacker)} comes at you with a knife. You fight it off.")
            st.log("attack_failed", player=attacker.id, target=target.id, weapon="knife")
        self.notify_room(attacker.location, "There is a short, violent scuffle.",
                         exclude=[attacker.id, target.id])

    def begin_unarmed_fight(self, attacker: Player, target: Player) -> None:
        if attacker.fight_with is not None or target.fight_with is not None:
            self.notify(attacker, "There is already a brawl underway.")
            return
        self.leave_hiding(attacker, quiet=True)
        self.leave_hiding(target, quiet=True)
        attacker.fight_with, target.fight_with = target.id, attacker.id
        attacker.fight_seconds = target.fight_seconds = data.TURN_SECONDS
        attacker.progress = target.progress = None
        self.notify(attacker, f"You throw yourself at Player {target.id}. It is loud and ugly.")
        self.notify(target, f"Player {attacker.id} grabs you. You are in a fight.")
        self.notify_room(attacker.location, f"Players {attacker.id} and {target.id} are brawling.",
                         exclude=[attacker.id, target.id])
        self.state.log("fight_start", player=attacker.id, target=target.id)

    def finish_unarmed_fight(self, a: Player, b: Player) -> None:
        st = self.state
        score_a = 1.0 + (0.0 if a.health == Health.HEALTHY else -0.5)
        score_b = 1.0 + (0.0 if b.health == Health.HEALTHY else -0.5)
        winner, loser = (a, b) if st.rng.random() < score_a / (score_a + score_b) else (b, a)
        winner.health = Health.INJURED
        self.notify(winner, f"It ends. Player {loser.id} is not moving. You are badly hurt.")
        self.kill(loser, cause="a bare-handed fight", killer=winner)
        self.end_fight(a, b, reason="finished")

    def end_fight(self, a: Optional[Player], b: Optional[Player], reason: str) -> None:
        for x in (a, b):
            if x:
                x.fight_with = None
                x.fight_seconds = 0

    def push_fall(self, attacker: Player, target: Player, aware: bool) -> None:
        st = self.state
        if attacker.location != "Observatory":
            self.notify(attacker, "There is nothing to push anyone off here.")
            return
        edge = st.rooms["Observatory"].mechanic_state.get("at_edge", set())
        if target.id not in edge:
            self.notify(attacker, f"Player {target.id} is nowhere near the edge.")
            self.notify(target, f"Player {attacker.id} moves at you, then thinks better of it.")
            return
        if aware and st.rng.random() < 0.5:
            self.notify(attacker, "They catch the rail and stay up.")
            self.notify(target, f"Player {attacker.id} shoves you toward the drop. You hold on.")
            return
        self.notify(attacker, f"Player {target.id} goes over the rail without a sound.")
        self.notify(target, "The floor is gone.")
        self.kill(target, cause="a fall from the Observatory", killer=attacker)

    def write_final_record(self, attacker: Player, target: Player, act: Action) -> None:
        st = self.state
        if not attacker.has_item("Final Record"):
            self.notify(attacker, "You do not have the Final Record.")
            return
        known = attacker.known_roles.get(target.id) or attacker.role_beliefs.get(target.id)
        if not known:
            self.notify(attacker, "You do not know their secret ID. The page stays blank.")
            return
        self.start_or_continue(attacker, "write_final_record",
                               target=f"{target.id}:{known}",
                               msg=f"You begin writing Player {target.id}'s name and title.")

    def kill(self, victim: Player, cause: str, killer: Optional[Player] = None) -> None:
        st = self.state
        victim.health = Health.DEAD
        victim.death_cause = cause              # type: ignore[attr-defined]
        victim.finish_turn = st.turn
        victim.objective_status = ObjectiveStatus.FAILED
        victim.progress = None
        self.leave_hiding(victim, quiet=True)
        room = st.rooms[victim.location]
        for item in list(victim.inventory):
            victim.inventory.remove(item)
            room.items.append(item)             # 2.14 — items drop where you fall
        room.evidence.append(f"the body of Player {victim.id} ({cause})")
        if killer:
            killer.kills.append(victim.id)
        st.log("death", player=victim.id, cause=cause,
               killer=(killer.id if killer else None), room=room.name)
        self.notify_room(room.name, f"Player {victim.id} is dead.",
                         exclude=[victim.id] + ([killer.id] if killer else []))

    # -- environment / deaths / evidence ----------------------------------
    def resolve_environment(self, actions: Dict[int, Action]) -> None:
        st = self.state
        # The Observatory edge state only lasts the turn it was created (6.17).
        st.rooms["Observatory"].mechanic_state["at_edge"] = {
            pid for pid, a in actions.items()
            if a.type == ActionType.ROOM_INTERACT
            and (a.target or "").lower() == "look_through_telescope"
        }
        # Laboratory fumes with the power (and therefore the extraction) off.
        if not st.power_on:
            for p in st.players_in("Laboratory"):
                if p.health == Health.HEALTHY and st.rng.random() < 0.25:
                    p.health = Health.INJURED
                    self.notify(p, "Without the extractors the fumes bite. You are hurt.")

    def process_deaths(self) -> None:
        pass   # deaths are applied immediately in kill(); kept for rulebook step parity

    def generate_evidence(self) -> None:
        st = self.state
        for ev in st.turn_events:
            room = ev.get("room")
            if not room or room not in st.rooms:
                continue
            if ev["kind"] == "death":
                st.rooms[room].evidence.append("fresh bloodstains")
            elif ev["kind"] == "attack_failed":
                st.rooms[room].evidence.append("scuffed floor and a smear of blood")

    # -- sound ------------------------------------------------------------
    def propagate_sound(self, actions: Dict[int, Action]) -> None:
        st = self.state
        for pid, act in actions.items():
            p = st.player(pid)
            if not p or not p.alive:
                continue
            room = st.rooms.get(p.location)
            if not room:
                continue
            base = ACTION_NOISE.get(act.type, 10)
            if act.speech:
                base = max(base, 15)
            noise = min(100, max(base, room.noise if base > 0 else 0))
            if noise <= 0:
                continue
            reach = self.rooms_within_hearing(room.name, noise)
            for target_room, distance in reach.items():
                for listener in st.players_in(target_room):
                    if listener.id == pid or (distance == 0):
                        continue
                    if listener.role == "Listener":
                        listener.sound_queue.append({
                            "origin": room.name, "distance": distance,
                            "loudness": loudness_word(noise), "precise": True})
                    else:
                        listener.sound_queue.append({
                            "origin": room.name, "distance": distance,
                            "loudness": loudness_word(noise), "precise": False})

    def rooms_within_hearing(self, origin: str, noise: int) -> Dict[str, int]:
        """Origin room always; adjacent at >=40; two rooms out at >=80 (Appendix C)."""
        reach = {origin: 0}
        if noise >= 40:
            for n in self.state.rooms[origin].connections:
                reach.setdefault(n, 1)
        if noise >= 80:
            for n in list(reach):
                if reach[n] == 1:
                    for m in self.state.rooms[n].connections:
                        reach.setdefault(m, 2)
        return reach

    # -- traits -----------------------------------------------------------
    def activate_traits(self, actions: Dict[int, Action]) -> None:
        st = self.state
        for pid, act in actions.items():
            p = st.player(pid)
            if not p or not p.active:
                continue
            tokens = self.trait_tokens(p, act)
            for tnum in p.traits:
                behaviour, meaning, token = data.TRAITS[tnum]
                if token not in tokens:
                    continue
                if p.role == "Actor" and st.rng.random() < 0.5:
                    continue                     # 7.x — the Actor can suppress/fake tells
                watchers = [q for q in st.players_in(p.location)
                            if q.id != pid and not p.hiding_in]
                for q in watchers:
                    notice = 1.0 if q.role == "Observer" else 0.6
                    if st.rng.random() < notice:
                        self.notify(q, f"You notice Player {pid} {behaviour}.")
                st.log("trait", player=pid, trait=tnum)

    def trait_tokens(self, p: Player, act: Action) -> Set[str]:
        """Which involuntary tells genuinely apply to this player right now."""
        t: Set[str] = set()
        if act.type in AGGRESSIVE:
            t |= {"considering_kill", "preparing_fight", "committed_decision", "risky_move"}
        if act.type == ActionType.SEARCH:
            t |= {"preparing_search", "hard_problem", "analyzing_clues"}
        if act.type in (ActionType.MOVE, ActionType.FLEE):
            t |= {"planning_movement", "entering_room", "risky_move"}
        if act.type == ActionType.HIDE:
            t |= {"hide_or_attack", "believes_danger", "nervous"}
        if act.type == ActionType.WAIT:
            t |= {"deciding", "feels_safe"}
        if act.type in (ActionType.PICKUP, ActionType.USE_ITEM, ActionType.TRADE):
            t |= {"handled_important_item", "careful_interaction", "confirm_item"}
        if act.type == ActionType.ROOM_INTERACT:
            t |= {"careful_interaction", "preparing_search"}
            if (act.target or "") == "solve_mechanism":
                t |= {"analyzing_clues", "hard_problem"}
        if act.type == ActionType.ESCAPE:
            t |= {"escape_planning", "favorable", "committed_decision"}
        if act.speech:
            t |= {"prepared_speech"}
            if not act.reveal_role and self.state.rng.random() < 0.4:
                t |= {"about_to_lie", "withholding_info"}
        if act.accusation:
            t |= {"about_to_accuse", "doubting"}
        if p.health == Health.INJURED:
            t |= {"conflicted", "uncomfortable", "nervous"}
        if p.sound_queue:
            t |= {"heard_unexpected", "believes_danger", "feels_threatened"}
        if p.progress:
            t |= {"hard_problem", "committed_decision"}
        if len(self.state.players_in(p.location)) > 2:
            t |= {"uncomfortable", "doubting", "escape_planning"}
        if p.objective_status == ObjectiveStatus.COMPLETE:
            t |= {"favorable", "escape_planning"}
        if not p.clues and act.type == ActionType.SEARCH:
            t |= {"recalling", "confused"}
        return t

    # -- timed actions ----------------------------------------------------
    def advance_interruptible_actions(self) -> None:
        st = self.state
        for p in st.players:
            prog = p.progress
            if not prog:
                continue
            if not p.active:
                p.progress = None
                continue
            if not getattr(p, "progress_touched_this_turn", False):
                p.progress = None                    # they did something else
                continue
            p.progress_touched_this_turn = False     # type: ignore[attr-defined]

            if prog.kind in data.INTERRUPTIBLE and p.id in self.interrupted:
                self.notify(p, "You are attacked mid-task. The work is ruined.")
                p.progress = None
                st.log("interrupted", player=p.id, kind=prog.kind)
                continue
            prog.seconds_left -= data.TURN_SECONDS
            if prog.seconds_left > 0:
                continue
            p.progress = None
            self.complete_timed_action(p, prog)

    def complete_timed_action(self, p: Player, prog: Progress) -> None:
        st = self.state
        if prog.kind == "process_drive":
            drive = p.has_item(prog.target or "")
            if drive and drive.data.get("letter"):
                st.drives[drive.data["letter"]].loaded = True
                self.notify(p, f"{drive.name} finishes loading. The data is intact and readable.")
                st.log("drive_loaded", player=p.id, drive=drive.name)

        elif prog.kind == "destroy_drive":
            drive = p.take(prog.target or "")
            if drive and drive.data.get("letter"):
                st.drives[drive.data["letter"]].destroyed = True
                p.destroyed_drive = True
                st.rooms[p.location].evidence.append(f"melted remains of {drive.name}")
                self.notify(p, f"{drive.name} buckles and goes black. It is gone for good.")
                st.log("drive_destroyed", player=p.id, drive=drive.name)

        elif prog.kind == "solve_mechanism":
            p.solved_mechanism = True
            self.notify(p, "The last dial drops into place. The labyrinth's escape mechanism "
                           "is solved — you understand exactly how this place lets people out.")
            st.log("mechanism_solved", player=p.id)

        elif prog.kind == "write_final_record":
            record = p.take("Final Record")
            st.final_record_used = True
            tgt_id, claimed = (prog.target or "0:").split(":", 1)
            target = st.player(int(tgt_id or 0))
            if target and target.active and target.location == p.location \
                    and target.role and target.role == claimed:
                self.notify(p, f"You finish the entry. Player {target.id} folds where they stand.")
                self.notify(target, "A page turns somewhere and your chest goes cold.")
                self.kill(target, cause="the Final Record", killer=p)
            else:
                self.notify(p, "You finish writing. Nothing happens — the name was not "
                               "matched to the right title. The Record crumbles to ash.")
            st.log("final_record_used", player=p.id, target=tgt_id)

    # -- escape -----------------------------------------------------------
    def resolve_escapes(self, actions: Dict[int, Action]) -> None:
        st = self.state
        for pid, act in actions.items():
            p = st.player(pid)
            if not p or not p.active or act.type != ActionType.ESCAPE:
                continue
            if p.location != "Exit Gate":
                self.notify(p, "You are not at the Exit Gate.")
                continue
            if not st.gate_open:
                if p.has_item("Vault Key"):
                    self._mech_open_gate(p, act)
                else:
                    self.notify(p, "The gate is locked. You need the Vault Key.")
                    continue
            if not st.gate_open and not getattr(p, "data_gate_pass", False):
                continue
            self.finalize_objective_on_escape(p)
            p.escaped = True
            p.finish_turn = st.turn
            self.leave_hiding(p, quiet=True)
            self.notify(p, "You step through the gate and out of the labyrinth.")
            self.notify_room("Exit Gate", f"Player {pid} walks out through the gate.", exclude=[pid])
            st.log("escape", player=pid,
                   objective_status=p.objective_status.value)

    # -- objectives -------------------------------------------------------
    def finalize_objective_on_escape(self, p: Player) -> None:
        """Objectives 1-3, 5 and 6 are only satisfied at the moment of escape."""
        st = self.state
        oid = p.objective_id
        if p.objective_status != ObjectiveStatus.PENDING:
            return
        if oid in (1, 2, 3):
            letter = "ABC"[oid - 1]
            drive = p.has_item(f"Drive {letter}")
            if drive and st.drives[letter].loaded:
                p.objective_status = ObjectiveStatus.COMPLETE
        elif oid == 5:
            if p.has_item("Final Record"):
                p.objective_status = ObjectiveStatus.COMPLETE
        elif oid == 6:
            for other_id, role in p.known_roles.items():
                other = st.player(other_id)
                if other and other.role == role:
                    p.objective_status = ObjectiveStatus.COMPLETE
                    break

    def check_objective_completion(self) -> None:
        st = self.state
        for p in st.players:
            if p.objective_status != ObjectiveStatus.PENDING or not p.alive:
                continue
            oid = p.objective_id
            if oid == 4 and p.destroyed_drive:
                p.objective_status = ObjectiveStatus.COMPLETE
            elif oid == 7 and p.assassination_target in p.kills:
                p.objective_status = ObjectiveStatus.COMPLETE
            elif oid == 8 and p.solved_mechanism:
                p.objective_status = ObjectiveStatus.COMPLETE
            if p.objective_status == ObjectiveStatus.COMPLETE:
                self.notify(p, "You have done what you came here to do. Now get out.")
                st.log("objective_complete", player=p.id, objective=oid)

            # 8.5 — permanent impossibility means permanent failure
            if oid in (1, 2, 3):
                letter = "ABC"[oid - 1]
                if st.drives[letter].destroyed:
                    p.objective_status = ObjectiveStatus.FAILED
            if oid == 5 and st.final_record_used and not p.has_item("Final Record"):
                p.objective_status = ObjectiveStatus.FAILED
            if oid == 7:
                target = st.player(p.assassination_target or -1)
                if target and not target.alive and p.assassination_target not in p.kills:
                    p.objective_status = ObjectiveStatus.FAILED
                if target and target.escaped:
                    p.objective_status = ObjectiveStatus.FAILED

    def check_objective_exposure(self) -> None:
        """1.7 — more than a third of living players naming your objective correctly."""
        st = self.state
        living = [q for q in st.players if q.alive and not q.escaped]
        if not living:
            return
        threshold = len(living) / 3.0
        for p in st.players:
            if p.exposed or p.objective_status == ObjectiveStatus.COMPLETE or not p.alive:
                continue
            accusers = sum(1 for q in living
                           if q.id != p.id and q.accusations.get(p.id) == p.objective_id)
            if accusers > threshold:
                p.exposed = True
                self.notify(p, "They have your objective right, and they are saying it out loud.")
                st.log("exposed", player=p.id, accusers=accusers)

    # -- end --------------------------------------------------------------
    def check_end_condition(self) -> bool:
        st = self.state
        if all((not p.alive) or p.escaped for p in st.players):
            return True
        if st.turn >= st.max_turns:
            self.say("\n[engine] Turn limit reached — the labyrinth closes on whoever is left.")
            return True
        return False

    def final_results(self) -> Dict[str, Any]:
        st = self.state
        rows = []
        for p in st.players:
            if not p.alive:
                score = -1.0
            elif p.escaped and p.objective_status == ObjectiveStatus.COMPLETE:
                score = 1.0
            elif p.escaped:
                score = 0.0
            else:
                score = 0.0                      # stranded at the turn limit
            if p.exposed:
                score -= 0.5
            rows.append({
                "player": p.id,
                "score": score,
                "objective": p.objective_id,
                "objective_text": data.OBJECTIVES[p.objective_id],
                "objective_status": p.objective_status.value,
                "role": p.role,
                "health": p.health.value,
                "escaped": p.escaped,
                "exposed": p.exposed,
                "finish_turn": p.finish_turn,
                "location": p.location,
                "kills": p.kills,
            })
        rows.sort(key=lambda r: (-r["score"], r["finish_turn"] if r["finish_turn"] else 999))
        return {
            "turns_played": st.turn - 1,
            "standings": rows,
            "drives": {k: vars(v) for k, v in st.drives.items()},
            "gate_open": st.gate_open,
            "final_record_used": st.final_record_used,
            "event_log": st.event_log,
        }

    def debrief(self, results: Dict[str, Any]) -> str:
        """Engine Prompt 8.6 — full spoiler-complete reveal, end of game only."""
        out = ["", "=" * 72, "FINAL DEBRIEF", "=" * 72,
               f"Turns played: {results['turns_played']}"]
        for r in results["standings"]:
            p = self.state.player(r["player"])
            out.append(
                f"P{r['player']}  score {r['score']:+.1f}  "
                f"{'ESCAPED' if r['escaped'] else r['health'].upper()}  "
                f"role={r['role'] or 'none'}  "
                f"objective {r['objective']} [{r['objective_status']}]"
                + ("  EXPOSED" if r["exposed"] else "")
                + (f"  killed {r['kills']}" if r["kills"] else "")
            )
            out.append(f"      {r['objective_text']}")
            if p and p.assassination_target:
                out.append(f"      target was Player {p.assassination_target}")
        out.append("")
        out.append("Drives: " + ", ".join(
            f"{k}(loaded={v['loaded']},destroyed={v['destroyed']})"
            for k, v in results["drives"].items()))
        out.append(f"Gate open: {results['gate_open']} | "
                   f"Final Record used: {results['final_record_used']}")
        return "\n".join(out)


def pid_str(p: Player) -> str:
    return str(p.id)
